proj/Comment8or/Comment8or/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

proj/books/urls.py
from django.urls import path
from .views import admin_page, create_item, delete_item, item_list, update_item, register, login_view, send_email, \
    product_detail, cart_add, cart_remove, cart_detail, order_create, order_detail, order_cancel, order_purchase, \
    order_payment, profile_view, search_results
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', item_list, name='item_list'),
    path('admin_page/', admin_page, name='admin_page'),
    path('create_item/', create_item, name='create_item'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('update_item/<int:id>/', update_item, name='update_item'),
    path('search/', search_results, name='search_results'),
    path('accounts/login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('register/', register, name='register'),
    path('send_email/', send_email, name='send_email'),
    path('product/<str:name>/', product_detail, name='product_detail'),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<str:name>/', cart_add, name='cart_add'),
    path('cart/remove/<str:name>/', cart_remove, name='cart_remove'),
    path('order_create', order_create, name='order_create'),
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),
    path('order/<int:order_id>/cancel/', order_cancel, name='order_cancel'),
    path('order/purchase/<int:order_id>/', order_purchase, name='order_purchase'),
    path('order/payment/<int:order_id>/', order_payment, name='order_payment'),
]

proj/calc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='calculator')
]

proj/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/books/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Manager

class Item(models.Model):
    DoesNotExist = None
    objects = None
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='item_images/',default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

class LastViewed(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='last_viewed_items')
    item = models.ForeignKey('Item', on_delete=models.CASCADE)
    viewed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-viewed_at']
        unique_together = ('user', 'item')

    def __str__(self):
        return f'{self.user.username} viewed {self.item.name} at {self.viewed_at}'

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    payment_status = models.CharField(max_length=20, default='без статуса')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Item, related_name='order_items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

class Book(models.Model):
    objects = Manager()
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255,default='')
    publisher = models.CharField(max_length=255)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

    def overall_rating(self):
        ratings = self.reviews.values_list('rating', flat=True)
        return sum(ratings) / len(ratings) if ratings else 0

class Review(models.Model):
    book = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    comment = models.TextField(default='')
    date = models.DateField()
    modified_date = models.DateField(null=True, blank=True)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)],default=0)

    def __str__(self):
        return self.comment

class Contributor(models.Model):
    first_names = models.CharField(max_length=50)
    last_names = models.CharField(max_length=50)

    def initialled_name(self):
        initials = [name[0].upper() for name in self.first_names.split()]
        return f"{self.last_names}, {' '.join(initials)}"

    def __str__(self):
        return self.initialled_name()

proj/books/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Order

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=100, label='Quantity')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quantity'].widget.attrs.update({'class': 'form-control col-md-2 mr-2'})
        self.fields['update'].widget.attrs.update({'class': 'd-none'})

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['postal_code'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control'})

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    age = forms.IntegerField(required=True)
    gender = forms.CharField(required=True, max_length=10)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'age', 'gender')

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if len(password1) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError("Password must contain at least one number.")
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError("Password must contain at least one uppercase letter.")
        if not any(char.islower() for char in password1):
            raise forms.ValidationError("Password must contain at least one lowercase letter.")
        return password1

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists.")
        return username

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    error_messages = {
        'invalid_login': 'Please enter a correct %(username)s and password. Note that both fields may be case-sensitive.',
        'inactive': 'This account is inactive.',
    }

    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': True})

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

proj/books/views.py
from django.utils import timezone
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db.models import Max
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from .cart import Cart
from django.contrib.auth import authenticate
from .forms import CustomUserCreationForm, CustomAuthenticationForm, CartAddProductForm, OrderCreateForm
from django.core.mail import send_mail, BadHeaderError
from .models import Item, OrderItem, Order, LastViewed
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q

def admin_page(request):
    items = Item.objects.all()
    context = {'items': items}
    return render(request, 'books/admin.html', context)

@login_required
def item_list(request):
    items = Item.objects.all()
    last_viewed_items = LastViewed.objects.filter(user=request.user).order_by('-viewed_at')[:5]
    return render(request, 'books/base.html', {'items': items, 'last_viewed_items': last_viewed_items})

def create_item(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        price = request.POST['price']
        image = request.FILES.get('image')
        max_id = Item.objects.all().aggregate(Max('id'))['id__max']
        if max_id is None:
            new_id = 1
        else:
            new_id = max_id + 1
        Item.objects.create(id=new_id, name=name, description=description, price=price, image=image)
        return redirect('item_list')
    else:
        return render(request, 'books/create_item.html')

def update_item(request, id):
    item = get_object_or_404(Item, id=id)
    if request.method == 'POST':
        item.name = request.POST['name']
        item.description = request.POST['description']
        item.price = request.POST['price']
        item.image = request.FILES.get('image')
        item.__init__()
        return redirect('item_list')
    else:
        return render(request, 'books/update_item.html', {'item': item})

def delete_item(request, id):
    try:
        item = Item.objects.get(id=id)
    except Item.DoesNotExist:
        return HttpResponse('Item not found')
    item.delete()
    return redirect('admin_page')

def product_detail(request, name):
    item = get_object_or_404(Item, name=name)
    cart_product_form = CartAddProductForm()
    product_url = f"/product/{name}/"
    last_viewed, created = LastViewed.objects.get_or_create(user=request.user, item=item)
    last_viewed.viewed_at = timezone.now()
    last_viewed.save()
    return render(request, 'books/product_detail.html', {'item': item, 'product_url': product_url, 'cart_product_form': cart_product_form})

def search_results(request):
  query = request.GET.get('q')
  search = Item.objects.filter(
    Q(name__icontains=query) |
    Q(description__icontains=query)
  )
  context = {'search': search, 'query': query}
  return render(request, 'books/search.html', context)


@require_POST
def cart_add(request, name):
    cart = Cart(request)
    product = get_object_or_404(Item, name=name)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart_detail')

def cart_remove(request, name):
    cart = Cart(request)
    product = get_object_or_404(Item, name=name)
    cart.remove(product)
    return redirect('cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'books/cart_detail.html', {'cart': cart})

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            cart.clear()
            messages.success(request, 'Your order has been created')
            return redirect('order_detail', order_id=order.id)
    else:
        form = OrderCreateForm()
    return render(request, 'books/order_create.html', {'form': form})

def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'books/order_detail.html', {'order': order})

@require_POST
def order_cancel(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.payment_status = 'отменен'
    order.save()
    return redirect('order_detail', order_id=order_id)

def order_purchase(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'books/order_purchase.html', {'order': order})

def order_payment(request, order_id):
    if request.method == 'POST':
        order = Order.objects.get(id=order_id)
        order.payment_status = 'оплачен'
        order.save()
        messages.success(request, f"Order {order_id} has been purchased!")
        return redirect(reverse('order_detail', kwargs={'order_id': order_id}))

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/login/')
    else:
        form = CustomUserCreationForm()
    return render(request, 'books/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                form.add_error(None, 'Invalid username or password.')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'books/login.html', {'form': form})

@login_required
def profile_view(request):
    user = request.user
    orders = Order.objects.all()
    if request.method == 'POST':
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.save()
    return render(request, 'books/profile.html', {'orders': orders})

def send_email(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        try:
            send_mail('Мечтать не вредно! 🥰 Подтвердите подписку', 'Мечта ближе, чем можно представить', '210107181@stu.sdu.edu.kz', [email])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return redirect('item_list')

proj/books/templates/books/admin.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Admin Page</h1>
        <h2>Items</h2>
        <ul class="list-group">
            {% for item in items %}
                <li class="list-group-item">{{ item.name }} - {{ item.description }} - {{ item.price }}
                    <form method="POST" action="{% url 'delete_item' item.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm float-right">Delete</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

proj/books/templates/books/book_list.html
{% extends 'books/base.html' %}

{% block content %}
  <h1>Book List</h1>
  <ul>
    {% for book in books %}
      <li>{{ book.title }} by {{ book.author }}</li>
      <button><a href="{% url 'book_details' pk=book.pk %}" class="text-decoration-none">Reviews</a></button>
    {% empty %}
      <li>No books found.</li>
    {% endfor %}
  </ul>
{% endblock %}

proj/books/templates/books/cart_detail.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
<form method="POST" action="{% url 'order_create' %}">
    <h1>Your cart</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        <tr>
            <td>
                <a href="{% url 'product_detail' item.product.name %}">{{ item.product.name }}</a>
            </td>
            <td>{{ item.price }} ₸</td>
            <td>
                <form action="{% url 'cart_add' item.product.name %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-secondary">Update</button>
                        </div>
                    </div>
                    <input type="hidden" name="update" value="True">
                </form>
            </td>
            <td>
                <a href="{% url 'cart_remove' item.product.name %}" class="btn btn-danger btn-sm">
                    Remove
                </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Your cart is empty</td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td colspan="2"></td>
            <th>Total:</th>
            <td>{{ cart.get_total_price }}</td>
        </tr>
        </tfoot>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Create Order</button>
</form>
{% endblock %}

proj/books/templates/books/create_item.html
<!DOCTYPE html>
<html>
<head>
  <title>Form Example</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <h2>Create Item</h2>
  <form class="form-group" method="POST" action="{% url 'create_item' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <label for="image">Upload a image:</label>
    <input class="form-control-file" type="file" name="image" accept="image/*">
    <br>
    <label for="name">Name:</label>
    <input class="form-control" type="text" name="name" required>
    <br>
    <label for="description">Description:</label>
    <textarea class="form-control" name="description" required></textarea>
    <br>
    <label for="price">Price:</label>
    <input class="form-control" type="number" name="price" required>
    <br>
    <button class="btn btn-primary" type="submit">Create item</button>
  </form>
</body>
</html>

proj/books/templates/books/login.html
<form method="post" class="form-horizontal">
    {% csrf_token %}
    <h1>Логин</h1>
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for field, errors in form.errors.items %}
        <strong>{{ field|title }}:</strong>
        {% for error in errors %}
        <span>{{ error }}</span>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
        {{ form.username.label_tag }}
        {{ form.username }}
    </div>
    <div class="form-group">
        {{ form.password.label_tag }}
        {{ form.password }}
    </div>
    <button type="submit" class="btn btn-primary btn-block">Login</button>
</form>

<style>
body {
  background-image: url('background-image.jpg');
  background-size: cover;
  background-position: center center;
}

.form-horizontal {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin: 50px auto;
  max-width: 400px;
  padding: 20px;
  border: 2px solid #ddd;
  border-radius: 10px;
  background-color: rgba(255, 255, 255);
}

.form-group {
  width: 100%;
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  font-size: 16px;
  font-weight: bold;
  margin-bottom: 5px;
}

.form-group input {
  display: block;
  width: 100%;
  height: 50px;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 10px;
  font-size: 16px;
  font-family: sans-serif;
  background-color: #f8f8f8;
}

.form-group input:focus {
  outline: none;
  border-color: #007bff;
}

.form-group .text-danger {
  color: red;
  margin-top: 5px;
}

.btn {
  width: 100%;
  height: 50px;
  display: inline-block;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  font-size: 16px;
  font-weight: bold;
  color: #fff;
  background-color: #007bff;
  cursor: pointer;
  transition: background-color 0.2s ease-in-out;
}

.btn:hover {
  background-color: #0062cc;
}

.btn:active {
  transform: translateY(2px);
}

</style>

proj/books/templates/books/order_create.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
  <h1>Информация о покупателя</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_first_name">Имя</label>
      {{ form.first_name }}
    </div>
    <div class="form-group">
      <label for="id_last_name">Фамилия</label>
      {{ form.last_name }}
    </div>
    <div class="form-group">
      <label for="id_email">Емайл</label>
      {{ form.email }}
    </div>
    <div class="form-group">
      <label for="id_address">Адрес</label>
      {{ form.address }}
    </div>
    <div class="form-group">
      <label for="id_postal_code">Почтовый индекс</label>
      {{ form.postal_code }}
    </div>
    <div class="form-group">
      <label for="id_city">Город</label>
      {{ form.city }}
    </div>
    <button type="submit" class="btn btn-success">Продолжить</button>
  </form>
{% endblock %}

proj/books/templates/books/order_detail.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
<h1>Заказ {{ order.id }}</h1>
<p>Созданный: {{ order.created }}</p>
<p>Последнее обновление: {{ order.updated }}</p>
<p>Статус: {{ order.payment_status }}</p>
<p>Итого: {{ order.get_total_cost }} ₸</p>
<h2>Корзина</h2>
<table class="table">
    <thead>
    <tr>
        <th>Наименование</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
    {% for item in order.items.all %}
    <tr>
        <td>{{ item.product.name }}</td>
        <td>{{ item.price }} ₸</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.get_cost }} ₸</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">В корзине пока ничего нет</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if order.payment_status != 'оплачен' %}
<form method="post" action="{% url 'order_purchase' order_id=order.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Продолжить</button>
</form>
{% endif %}
{% if order.payment_status != 'отменен' %}
<form method="post" action="{% url 'order_cancel' order_id=order.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Отклонить заказ</button>
</form>
{% endif %}
{% endblock %}

proj/books/templates/books/order_purchase.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
  <h1>Подтверждения заказа</h1>
  <form method="post" action="{% url 'order_payment' order_id=order.id %}">
    {% csrf_token %}
    <label for="card_number">Номер карты:</label>
    <input type="text" id="card_number" name="card_number" required>
    <br>
    <label for="expiration_date">Дата окончания срока:</label>
    <input type="text" id="expiration_date" name="expiration_date" required>
    <br>
    <label for="security_code">Код безопасности:</label>
    <input type="text" id="security_code" name="security_code" required>
    <br>
    <button type="submit" class="btn btn-success">Оформить заказ:</button>
  </form>
{% endblock %}

proj/books/templates/books/product_detail.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <img src="{{ item.image.url }}" alt="{{ item.name }}" class="img-fluid">
    </div>
    <div class="col-md-6">
      <h2>{{ item.name }}</h2>
      <p class="lead">{{ item.description }}</p>
      <p class="h3 font-weight-bold">{{ item.price }} ₸</p>
      <form action="{% url 'cart_add' item.name %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="quantity">Quantity</label>
          <input type="number" id="quantity" name="quantity" value="1" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary btn-lg">
          Add to Cart
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

proj/books/templates/books/search.html
{% extends 'books/base.html' %}

{% block productt %}{% endblock %}
{% block product2 %}{% endblock %}
{% block product3 %}{% endblock %}
{% block content %}
<div class="productt">Результаты поиска для {{ query }}</div>
<div class="product-nav">
    {% for item in search %}
    <div class="product-card">
        <div class="product-image">
            {% if item.image %}
            <a href="{% url 'product_detail' item.name %}">
                <img src="{{ item.image.url }}" alt="{{ item.name }}">
            </a>
            {% endif %}
        </div>
        <div class="product-name">
            <a href="{% url 'product_detail' item.name %}">{{ item.name }}</a>
        </div>
        <div class="product-description">
            <span class="bonus-sticker">{{ item.description }}</span>
        </div>
        <div class="product-prices">
            <span class="product-price">{{ item.price }} ₸</span>
        </div>
    </div>
    {% empty %}
    <p>Нет результатов поиска.</p>
    {% endfor %}
</div>
{% endblock %}

proj/books/templates/books/update_item.html
<!DOCTYPE html>
<html>
<head>
  <title>Form Example</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2>Update Item</h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="image">Image:</label>
            <input type="file" class="form-control-file" id="image" name="image">
          </div>
          <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ item.name }}">
          </div>
          <div class="form-group">
            <label for="description">Description:</label>
            <textarea class="form-control" id="description" name="description">{{ item.description }}</textarea>
          </div>
          <div class="form-group">
            <label for="price">Price:</label>
            <input type="text" class="form-control" id="price" name="price" value="{{ item.price }}">
          </div>
          <button type="submit" class="btn btn-primary">Update Item</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
</body>
</html>